version: '3.8'
# https://www.keycloak.org/server/containers
services:
  keycloak:
      image: quay.io/keycloak/keycloak
      command:
        - start
      environment:
        #see https://www.keycloak.org/server/all-config
        - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
        - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
        - KC_HOSTNAME_URL=${KEYCLOAK_SERVER}
        - KC_HTTP_ENABLED=true
        # see https://github.com/keycloak/keycloak/issues/14586
        - KC_HOSTNAME_STRICT=false
        - KC_PROXY=edge
        - PROXY_ADDRESS_FORWARDING=true
        #- KC_HTTP_RELATIVE_PATH: /auth
      #ports:
      #  - 8080:8080
      #volumes:
        #- ./keystore.p12:/keystore.p12
        #- ./export_data:/export_data