# this files shows how to use caddy as a reverse proxy
# requires https://github.com/lucaslorentz/caddy-docker-proxy
# and a existing docker network 'caddy'

version: '3.8'
services:
    keycloak:
        networks:
            - default
            - caddy
        labels:
            caddy_01: ${KEYCLOAK_SERVER}
            caddy_01.reverse_proxy: "{{upstreams 8080}}"
  
networks:
  # Add caddy as an external network.
  caddy:
    external: true
