version: '3.8'
# https://www.keycloak.org/server/containers
services:
  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
  keycloak:
      image: quay.io/keycloak/keycloak
      command:
        - start
      environment:
        #see https://www.keycloak.org/server/all-config
        #DB params are optional. If not set, internal h2 DB is used
        - KC_DB=postgres
        - KC_DB_URL_HOST=postgres
        - KC_DB_URL_PORT=5432
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_SCHEMA=public
        - KC_DB_PASSWORD=password
        - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
        - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
        - KC_HOSTNAME_URL=${KEYCLOAK_SERVER}
        - KC_HTTP_ENABLED=true
        # see https://github.com/keycloak/keycloak/issues/14586
        - KC_HOSTNAME_STRICT=false
        - KC_PROXY=edge
        - PROXY_ADDRESS_FORWARDING=true
        #- KC_HTTP_RELATIVE_PATH: /auth
      #ports:
      #  - 8080:8080
      #volumes:
        #- ./keystore.p12:/keystore.p12
        #- ./export_data:/export_data
      depends_on:
        - postgres